# Tensor operations

### Assignment 1

 A **tensor** is a number, vector, matrix or any n-dimensional array
- torch.from_numpy
- torch.randn
- torch.zeros
- torch.nn.Linear
- torch.nn.Sequential

In [1]:
import torch
import numpy as np

## Function 1 - torch.from_numpy
##### Syntax:  torch.from_numpy(ndarray) → Tensor

It creates a Tensor from a numpy.ndarray.
The returned tensor and ndarray share the same memory. Modifications to the tensor will be reflected in the ndarray and vice versa. The returned tensor is not resizable.

In [2]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [3]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

2 * 2 Integer array to tensor

In [4]:
X_train = np.array([[1,0,0,0,0,0],[0,0,0,0,0,1],[0,1,0,0,0,0]])
X_train

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0]])

In [5]:
Y_train = torch.from_numpy(X_train)
Y_train

tensor([[1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0]])

6 * 3 Integer Array to Tensor

In [6]:
x = np.array([[1.6, 2.3], [3.4, 4.5, 5.]])
x

array([list([1.6, 2.3]), list([3.4, 4.5, 5.0])], dtype=object)

In [7]:
y = torch.from_numpy(x)
y

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

2 * 2 Float Array to 1-D Tensor with dtype:'object'

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

## Function 2 - torch.randn

We use PyTorch Tensors to fit a two-layer network to random data

In [16]:
# N is batch size; D_in is input dimension;
# H is hidden dimension
N, D_in = 4, 6
x = torch.randn(N, D_in, device=torch.device("cpu"), dtype=torch.float)
x

tensor([[-1.5166, -0.1861,  0.6441,  2.3332,  0.0760,  0.3239],
        [ 1.3109, -0.6170, -0.4137, -1.3525,  0.6272, -0.9855],
        [ 1.7450, -0.2459, -0.2232,  0.2839,  0.3878, -0.4933],
        [-1.3300, -0.7048, -1.8311,  0.5819,  0.1400, -0.7759]])

**torch.rand()** with all parameters

In [17]:
torch.randn(7,6)

tensor([[ 5.0968e-01,  1.9004e-02, -1.6723e+00, -7.8863e-01, -5.2397e-01,
          1.8063e+00],
        [-3.8569e-02,  1.3991e-01, -4.6519e-01,  7.0421e-01, -1.1453e+00,
         -9.0912e-01],
        [ 1.6188e+00, -3.0098e-01, -1.2335e+00, -3.4928e-01, -3.5742e-01,
          1.9599e+00],
        [ 1.0164e+00,  5.4662e-01, -2.5661e-04,  4.1119e-01, -3.9522e-01,
          6.5492e-01],
        [ 3.6855e-01,  5.2588e-01,  4.3456e-01, -1.0065e+00,  7.8093e-02,
         -1.2312e+00],
        [-2.4395e+00,  2.9985e-01,  1.5079e-01, -4.6530e-03,  1.3019e+00,
         -6.9363e-01],
        [-8.1086e-01, -1.5135e-01,  4.0341e-01, -6.9825e-02, -1.3468e+00,
          8.6610e-01]])

**torch.randn()** with only dimensions.

In [18]:
torch.randn(3, 4, dtype=torch.int64)

RuntimeError: "norma_cpu" not implemented for 'Long'

**torch.randn()** with only dimensions and dtype as int.

torch.randn() 

## Function 3 - torch.zeros

Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

**Syntax:** torch.zeros(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

In [19]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

2-D tensor with all zeroes

In [20]:
torch.zeros(2, 3, 8)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])

3-D tensor with all zeroes

In [21]:
torch.zeros(1.9)

TypeError: zeros(): argument 'size' (position 1) must be tuple of ints, not float

Function with float dimensions

Except the size of the function all the other parameters are optional.

## Function 4 - torch.nn.Linear

Applies a linear transformation to the incoming data: **y = xA^T + b**

In [22]:
m = torch.nn.Linear(20, 30)
input = torch.randn(128, 20)

In [23]:
output = m(input)
output.size()

torch.Size([128, 30])

The above example does linear transformation

In [24]:
x = torch.tensor([[1.0, -1.0],
                  [0.0,  1.0],
                  [0.0,  0.0]])

in_features = x.shape[1]  # = 2
out_features = 2

m = torch.nn.Linear(in_features, out_features)
m

Linear(in_features=2, out_features=2, bias=True)

Another example for linear tranformation

In [25]:
m = torch.nn.Linear(20, 30)
input = torch.randn(12, 80)
output = m(input)
output.size()

RuntimeError: size mismatch, m1: [12 x 80], m2: [20 x 30] at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorMath.cpp:41

Example with inproper dimensions.

This function does linear tranformation of the tensors.

## Function 5 - torch.nn.Sequential

**torch.nn.Sequential(*args)**

A sequential container. 
Modules will be added to it in the order they are passed in the constructor.

In [27]:
torch.nn.Sequential(
          torch.nn.Conv2d(1,20,5),
          torch.nn.ReLU(),
          torch.nn.Conv2d(20,64,5),
          torch.nn.ReLU()
        )

Sequential(
  (0): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU()
  (2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  (3): ReLU()
)

Example of using Sequential

In [30]:
from collections import OrderedDict

torch.nn.Sequential(OrderedDict([
          ('conv1', torch.nn.Conv2d(1,20,5)),
          ('relu1', torch.nn.ReLU()),
          ('conv2', torch.nn.Conv2d(20,64,5)),
          ('relu2', torch.nn.ReLU())
        ]))

Sequential(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (relu1): ReLU()
  (conv2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  (relu2): ReLU()
)

Example of using Sequential with OrderedDict

In [32]:
torch.nn.Sequential(
          torch.nn.Conv2d(0),
          torch.nn.Conv2d(0),
          torch.nn.ReLU()
        )

TypeError: __init__() missing 2 required positional arguments: 'out_channels' and 'kernel_size'

Example with inproper inputs

Alternatively, an ordered dict of modules can also be passed in.

## Conclusion

In this note book, we have discussed torch.from_numpy, torch.randn, torch.zeros, torch.nn.Linear, torch.nn.Sequential functions.

## Reference Links
Provide links to your references and other interesting articles about tensors
* https://pytorch.org/docs/stable/tensors.html
* https://pytorch.org/docs/master/generated/torch.nn.ModuleList.html
* https://pytorch.org/docs/stable/nn.html
* https://pytorch.org/tutorials/beginner/pytorch_with_examples.html

In [33]:
!pip install jovian --upgrade --quiet

In [34]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
